### ISSUE TITLE
Container is throwing error while trying to start

### ISSUE THREAD

**Issue by csharma2309** [aymenfurter/smartrag#12] opened 2024-10-12 08:12 UTC
Hello @aymenfurter, Really loved this project first of all. As I am trying to run and understand it, I am encountering an error

1. Took code.
2. Deployed using azd up

Getting error while tryin to access via URL. On deeper analysis found this error where container is failing to start due to a queue error. 

Which queue is this trying to access? Can you please help understand

2024-10-12T07:57:50.89243  Connecting to the container 'main'...
2024-10-12T07:57:50.91098  Successfully Connected to container: 'main' [Revision: 'rfp-app--6hr65cd-5cdc777dd7-qlrff', Replica: 'rfp-app--6hr65cd']
2024-10-12T07:56:47.253714943Z     exec("raise error from None")   # pylint: disable=exec-used # nosec
2024-10-12T07:56:47.253870736Z     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-12T07:56:47.253986083Z   File "<string>", line 1, in <module>
2024-10-12T07:56:47.254097943Z   File "/usr/local/lib/python3.11/site-packages/azure/storage/queue/_models.py", line 441, in _get_next_cb
2024-10-12T07:56:47.254387828Z     return self._command(number_of_messages=self.results_per_page)
2024-10-12T07:56:47.254533331Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-12T07:56:47.254644631Z   File "/usr/local/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
2024-10-12T07:56:47.254873330Z     return func(*args, **kwargs)
2024-10-12T07:56:47.255026649Z            ^^^^^^^^^^^^^^^^^^^^^
2024-10-12T07:56:47.255148808Z   File "/usr/local/lib/python3.11/site-packages/azure/storage/queue/_generated/operations/_messages_operations.py", line 285, in dequeue
2024-10-12T07:56:47.255401854Z     map_error(status_code=response.status_code, response=response, error_map=error_map)
2024-10-12T07:56:47.255555953Z   File "/usr/local/lib/python3.11/site-packages/azure/core/exceptions.py", line 161, in map_error
2024-10-12T07:56:47.255783010Z     raise error
2024-10-12T07:56:47.255935847Z azure.core.exceptions.ResourceNotFoundError: The specified queue does not exist.
2024-10-12T07:56:47.255945516Z RequestId:2e5b815a-4003-0020-267c-1cc1a9000000
2024-10-12T07:56:47.255950986Z Time:2024-10-12T07:56:47.2484090Z
2024-10-12T07:56:47.255956366Z **ErrorCode:QueueNotFound**
2024-10-12T07:56:47.255961606Z **Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>QueueNotFound</Code><Message>The specified queue does not exist.**
2024-10-12T07:56:47.255966745Z RequestId:2e5b815a-4003-0020-267c-1cc1a9000000
2024-10-12T07:56:47.256077344Z Time:2024-10-12T07:56:47.2484090Z</Message></Error>

Regards,
Chetan

**Comment by aymenfurter** [comment] 2024-10-12 09:40
Hey,

thanks for reporting this issue, happy to tale a look.

 does it persist when restarting the container? 
 
There are 2 queues. One for pending file uploads and one for pending index.

**Comment by csharma2309** [comment] 2024-10-12 10:09
@aymenfurter - thanks for answering over the weekend. Yes it persists. I should be seeing two queues in storage container, right? That's what you're referring to? 

BTW, did I miss any step or they get created during running of azd up command?

**Comment by aymenfurter** [comment] 2024-10-15 13:49
I'll need some time to investigate. Will get back to you within a couple of days.

**Comment by zhouyujn** [comment] 2024-10-20 03:26
I think I might be encountering a similar issue here.

Connecting...
2024-10-20T03:26:22.50931  Connecting to the container 'main'...
2024-10-20T03:26:22.53346  Successfully Connected to container: 'main' [Revision: 'smartragdemo-app--07oe7f1-64656bb6b5-lhtqs', Replica: 'smartragdemo-app--07oe7f1']
2024-10-20T03:22:58.093574478Z     exec("raise error from None")   # pylint: disable=exec-used # nosec
2024-10-20T03:22:58.093587733Z     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-20T03:22:58.093592432Z   File "<string>", line 1, in <module>
2024-10-20T03:22:58.093596990Z   File "/usr/local/lib/python3.11/site-packages/azure/storage/queue/_models.py", line 441, in _get_next_cb
2024-10-20T03:22:58.093601498Z     return self._command(number_of_messages=self.results_per_page)
2024-10-20T03:22:58.093606238Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-20T03:22:58.093611808Z   File "/usr/local/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
2024-10-20T03:22:58.093617208Z     return func(*args, **kwargs)
2024-10-20T03:22:58.093622247Z            ^^^^^^^^^^^^^^^^^^^^^
2024-10-20T03:22:58.093626996Z   File "/usr/local/lib/python3.11/site-packages/azure/storage/queue/_generated/operations/_messages_operations.py", line 285, in dequeue
2024-10-20T03:22:58.093632126Z     map_error(status_code=response.status_code, response=response, error_map=error_map)
2024-10-20T03:22:58.093637556Z   File "/usr/local/lib/python3.11/site-packages/azure/core/exceptions.py", line 161, in map_error
2024-10-20T03:22:58.093642465Z     raise error
2024-10-20T03:22:58.093647745Z azure.core.exceptions.ResourceNotFoundError: The specified queue does not exist.
2024-10-20T03:22:58.093652744Z RequestId:ae8e886a-1003-0000-209f-224daa000000
2024-10-20T03:22:58.093657603Z Time:2024-10-20T03:22:58.0868303Z
2024-10-20T03:22:58.093662773Z ErrorCode:QueueNotFound
2024-10-20T03:22:58.093667712Z Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>QueueNotFound</Code><Message>The specified queue does not exist.
2024-10-20T03:22:58.093672671Z RequestId:ae8e886a-1003-0000-209f-224daa000000
2024-10-20T03:22:58.093677430Z Time:2024-10-20T03:22:58.0868303Z</Message></Error>

**Comment by aymenfurter** [comment] 2024-10-20 14:40
Hi @csharma2309 and @zhouyujn,

The root cause of the issue was missing Azure storage queues, which I’ve now added in [PR #13](https://github.com/aymenfurter/smartrag/pull/13). The PR has been merged, so please pull the latest changes and redeploy the infrastructure. This should resolve the QueueNotFoundError and allow the container to start correctly.

I’ll go ahead and close this issue, but feel free to reopen or reach out if you experience any further issues.

Thanks again for your patience!

**Closed by aymenfurter** 2024-10-20 14:40 UTC
